### PR TITLE
Add open = FALSE argument

### PR DESCRIPTION
**Pull request by moldach**
Added the `open = FALSE` argument to the four functions

### CODE REVIEW

**Comment by maelle** [comment]
Thanks @moldach! A few comments to make this ready for merging
* Please document the new argument,
* Add `rstudioapi` to the list of required packages by running `usethis::use_package("rstudioapi")`,
 
Then run `devtools::document()`.

By the way ICYMI to have `devtools`/`usethis` functions always available in your R session, which is useful for developing packages, I've recently discovered you can run `usethis::use_devtools()` to add loading `devtools` to your .Rprofile.

**Comment by moldach** [comment]
>     * Please document the new argument,
> 
>     * Add `rstudioapi` to the list of required packages by running `usethis::use_package("rstudioapi")`,
> 
> 
> Then run `devtools::document()`.

Okay so I guess I forgot to document one function `createAnalysisProject` so I've now done that and added rstudioapi (thanks for tip about `.Rprofile`).  The travis CI build still seems to fail so I'm wondering what else needs to be done on my end.

Thanks!

**Comment by maelle** [comment]
:wave: @moldach! I cloned your branch because I was surprised at a failing test (it didn't fail any more :woman_shrugging: ) and took it as an opportunity to fix the PR. What was missing was the documentation of the parameter inside parameters list (in createBasicProject.R and createPackageProject.R, for createTrainingProject and createAnalysisProject we use `roxygen2`'s inherits tags to limit duplication cf https://blog.rstudio.com/2017/02/01/roxygen2-6-0-0/#improved-inheritance). Thanks a lot for your contribution!

**Comment by maelle** [comment]
Note for your next PR, it's better to make PR from a branch in your fork, e.g. you'd
* fork the repo
* clone your fork
* locally, `git checkout -b feature-name-or-so`
* work in this branch
* PR from `feature-name-or-so` to `master` of the upstream repo. 

This way it's easier for you to keep master of your fork up-to-date. When I forget to branch out before a PR, next time I use my fork, to update it I tend to delete and re-fork :see_no_evil: but I'm sure there are better ways.

**Comment by maelle** [comment]
Cf https://happygitwithr.com/fork-and-clone.html#dont-touch-master :smile_cat:

**Pull request merged**
