### PR TITLE
Issue #58 Make snake case name functions too

### PR DESCRIPTION
**Pull request by sgetalbo**
create_any_project aesthetic function names added to the end of the four function scripts as per Steph's first comment.

### CODE REVIEW

**Comment by maelle** [comment]
* Can you please remove the DS_store files?

* I don't see the Rd and NAMESPACE updates actually, did you forget to commit them?

**Comment by sgetalbo** [comment]
Hi @maelle - me and Steph fixed my git woes and I have removed the DS_store file and updated the master gitignore to include that so it won't crop up again. Also - .Rd files generated fine when I re-ran the devtools::document() command after I fixed my warnings, but even though I get a 'writing NAMESPACE' alert in my console, no new namespace file appears for me to push... any ideas?

**Comment by maelle** [comment]
:wave: here!

* it seems there are a few conflicts. we can resolve the one for tests/README.md at the very end but for the other ones please try to solve them (maybe by merging master into your branch).

* NAMESPACE was not updated. I think you need a `@export` `roxygen2` tag before each new function, and then run `document()` again.

* There are two ` .DS_store` files to be deleted.

Thank you!

**Comment by maelle** [comment]
Thanks! Now the only issue is that there are two .DS_store files to be deleted.

**Comment by maelle** [comment]
@sgetalbo thanks! can you resolve the conflicts? after that the PR should be ready to be merged.

**Pull request merged**
